export const TPL_MAIN_GET = 'TPL_MAIN_GET';
export const TPL_SECOND_GET = 'TPL_SECOND_GET';



export const TPL_THIRD_ONE_GET = 'TPL_THIRD_ONE_GET';
export const TPL_THIRD_TWO_GET = 'TPL_THIRD_TWO_GET';
export const TPL_THIRD_THREE_GET = 'TPL_THIRD_THREE_GET';




export const TPL_TABLE_LIST_GET = 'TPL_TABLE_LIST_GET';
export const TPL_TABLE_ITEM_SELECT = 'TPL_TABLE_ITEM_SELECT';
export const TPL_TABLE_ITEM_SELECT_ALL = 'TPL_TABLE_ITEM_SELECT_ALL';
export const TPL_TABLE_ITEM_SELECT_CANCEL = 'TPL_TABLE_ITEM_SELECT_CANCEL';
export const TPL_TABLE_ITEM_PUT = 'TPL_TABLE_ITEM_PUT';
export const TPL_TABLE_ITEM_POST = 'TPL_TABLE_ITEM_POST';
export const TPL_TABLE_ITEM_DELETE = 'TPL_TABLE_ITEM_DELETE';
export const TPL_TABLE_SEARCH_INIT = 'TPL_TABLE_SEARCH_INIT';
